services:
  - type: web
    name: painel-consultas
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    repo: https://github.com/nk3unico1533
    branch: main
